import {
  listGlossaryRows,
  listProductTranslationRows,
  runInTransaction,
  upsertProductTranslationRow,
  writeAudit,
} from "./db.js";
import { canonicalProductId } from "../../src/shared/i18n/productLocalization.js";
import { findCanonicalProduct, listCanonicalProducts } from "./productLocalizationStore.js";
import { bumpLocalizationCatalogVersion } from "./localizationVersion.js";
import { artifactFingerprint } from "./productAutoArtifact.js";
import {
  classifyPreparedItem,
  fingerprintMismatch,
  precomputeImportContext,
  summarizeClassification,
} from "./productAutoImportCore.js";

export {
  AUTO_IMPORT_FORMAT,
  AUTO_IMPORT_FORMAT_VERSION,
  loadAutoImportManifest,
  artifactFingerprint,
} from "./productAutoArtifact.js";

export { precomputeImportContext, classifyPreparedItem } from "./productAutoImportCore.js";

function nowIso() {
  return new Date().toISOString();
}

function importError(code, message, status = 409) {
  const error = new Error(message);
  error.code = code;
  error.status = status;
  return error;
}

function liveImportContext() {
  return precomputeImportContext(
    listCanonicalProducts(),
    listGlossaryRows(),
    listProductTranslationRows()
  );
}

function assertFingerprints(loaded, ctx, expected = {}) {
  const mismatch = fingerprintMismatch(loaded, ctx);
  if (mismatch) {
    throw importError(mismatch, mismatch);
  }
  if (expected.runId && expected.runId !== loaded.manifest.runId) {
    throw importError("RUN_ID_MISMATCH", "Artifact runId does not match the approved run.");
  }
  if (expected.fingerprint && expected.fingerprint !== artifactFingerprint(loaded)) {
    throw importError("ARTIFACT_FINGERPRINT_MISMATCH", "Artifact fingerprint does not match the approved run.");
  }
  if (expected.baseMainSha && expected.baseMainSha !== loaded.manifest.baseMainSha) {
    throw importError("BASE_GUARD_MISMATCH", "Artifact base SHA does not match the approved run.");
  }
}

export function classifyProductAutoImport(loaded, ctx) {
  const counts = summarizeClassification(loaded, ctx);
  const fatal =
    counts.staleSource +
    counts.unknownProduct +
    counts.invalidLocale +
    counts.invalidField +
    counts.numericMismatch +
    counts.protectedMismatch +
    counts.emptyValue;
  return { counts, fatal };
}

export function dryRunFromContext(loaded, ctx, expected = {}) {
  assertFingerprints(loaded, ctx, expected);
  const { counts, fatal } = classifyProductAutoImport(loaded, ctx);
  return {
    mode: "dry-run",
    writes: 0,
    runId: loaded.manifest.runId,
    artifactBaseSha: loaded.manifest.baseMainSha || "",
    artifactCatalogFingerprint: loaded.manifest.wholeCatalogSourceFingerprint,
    currentCatalogFingerprint: ctx.catalogFingerprint,
    artifactGlossaryFingerprint: loaded.manifest.glossaryFingerprint,
    currentGlossaryFingerprint: ctx.glossaryFingerprint,
    catalogMatch: true,
    glossaryMatch: true,
    fatal,
    ...counts,
  };
}

export function dryRunProductAutoImport(loaded, products = listCanonicalProducts(), expected = {}) {
  const ctx = precomputeImportContext(products, listGlossaryRows(), listProductTranslationRows());
  return dryRunFromContext(loaded, ctx, expected);
}

function applyPreparedWrites(loaded, ctx, actor) {
  const { counts, fatal } = classifyProductAutoImport(loaded, ctx);
  if (fatal > 0) {
    throw importError("ARTIFACT_VALIDATION_FAILED", `Fatal AUTO import defects: ${fatal}`);
  }
  let inserted = 0;
  let updated = 0;
  let skippedManual = 0;
  let identical = 0;
  const stamp = nowIso();
  const provenance = {
    runId: loaded.manifest.runId,
    generatedAt: loaded.manifest.generatedAt,
  };
  for (const item of loaded.items) {
    const code = classifyPreparedItem(item, ctx);
    if (code === "wouldSkipMANUAL") {
      skippedManual += 1;
      continue;
    }
    if (code === "alreadyIdentical") {
      identical += 1;
      continue;
    }
    const existing =
      ctx.existingByKey.get(`${item.productId}\0${item.language}\0${item.field}`) || {
        productId: item.productId,
        languageCode: item.language,
        fieldKey: item.field,
        autoValue: "",
        autoSourceHash: "",
        autoRunId: "",
        autoGeneratedAt: "",
        manualValue: "",
        manualSourceHash: "",
      };
    upsertProductTranslationRow({
      ...existing,
      productId: item.productId,
      languageCode: item.language,
      fieldKey: item.field,
      autoValue: item.value,
      autoSourceHash: item.sourceHash,
      autoRunId: provenance.runId,
      autoGeneratedAt: provenance.generatedAt,
      manualValue: existing.manualValue || "",
      manualSourceHash: existing.manualSourceHash || "",
      updatedAt: stamp,
      updatedBy: actor,
    });
    if (code === "wouldUpdateAUTO") updated += 1;
    else inserted += 1;
  }
  const changed = inserted + updated > 0;
  if (changed) {
    bumpLocalizationCatalogVersion(actor || "product-auto-import");
  }
  writeAudit({
    action: "localization.product.auto.import",
    details: {
      runId: loaded.manifest.runId,
      artifactFingerprint: artifactFingerprint(loaded),
      catalogFingerprint: ctx.catalogFingerprint,
      glossaryFingerprint: ctx.glossaryFingerprint,
      inserted,
      updated,
      skippedManual,
      identical,
      languageCounts: counts.languageCounts,
      changed,
    },
  });
  return {
    mode: "apply",
    runId: loaded.manifest.runId,
    artifactBaseSha: loaded.manifest.baseMainSha || "",
    artifactCatalogFingerprint: ctx.catalogFingerprint,
    artifactGlossaryFingerprint: ctx.glossaryFingerprint,
    artifactFingerprint: artifactFingerprint(loaded),
    imported: inserted + updated,
    inserted,
    updated,
    skippedManual,
    identical,
    failed: 0,
    targetCells: loaded.items.length,
    catalogVersionBumped: changed,
  };
}

export function applyProductAutoImport(loaded, actor = "offline-auto-import", expected = {}) {
  return runInTransaction(() => {
    const ctx = liveImportContext();
    assertFingerprints(loaded, ctx, expected);
    return applyPreparedWrites(loaded, ctx, actor);
  });
}

export function findCanonicalProductSafe(productId) {
  return findCanonicalProduct(productId);
}

export { canonicalProductId };
