/**
 * True read-only Stage 4 AUTO dry-run. Does not import db.js.
 * Opens SQLite with { readOnly: true } and never creates schema.
 */
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync, realpathSync, statSync } from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { artifactFingerprint, loadAutoImportManifest } from "./productAutoArtifact.js";
import { fingerprintMismatch, precomputeImportContext, summarizeClassification } from "./productAutoImportCore.js";

function tableExists(db, name) {
  const row = db.prepare("SELECT 1 AS ok FROM sqlite_master WHERE type = 'table' AND name = ?").get(name);
  return Boolean(row);
}

function readJsonState(db, key) {
  if (!tableExists(db, "app_state")) return null;
  const row = db.prepare("SELECT value_json FROM app_state WHERE key = ?").get(key);
  if (!row?.value_json) return null;
  try {
    return JSON.parse(row.value_json);
  } catch {
    return null;
  }
}

function readGlossary(db) {
  if (!tableExists(db, "translation_glossary")) return [];
  return db
    .prepare(
      `SELECT id, source_ru AS sourceRu, language_code AS languageCode, target_value AS targetValue,
              context, protected
       FROM translation_glossary`
    )
    .all();
}

function readTranslations(db) {
  if (!tableExists(db, "product_translations")) return [];
  return db
    .prepare(
      `SELECT product_id AS productId, language_code AS languageCode, field_key AS fieldKey,
              auto_value AS autoValue, auto_source_hash AS autoSourceHash,
              auto_run_id AS autoRunId, auto_generated_at AS autoGeneratedAt,
              manual_value AS manualValue, manual_source_hash AS manualSourceHash
       FROM product_translations`
    )
    .all();
}

export function fileIdentity(dbPath) {
  const resolved = realpathSync(dbPath);
  const stat = statSync(resolved);
  return {
    path: resolved,
    size: stat.size,
    mtimeMs: stat.mtimeMs,
    sha256: createHash("sha256").update(readFileSync(resolved)).digest("hex"),
  };
}

export function semanticDbFingerprint(db) {
  const products = readJsonState(db, "products") || [];
  const settings = readJsonState(db, "localizationSettings") || {};
  const glossaryCount = tableExists(db, "translation_glossary")
    ? db.prepare("SELECT COUNT(*) AS n FROM translation_glossary").get().n
    : 0;
  const translationCount = tableExists(db, "product_translations")
    ? db.prepare("SELECT COUNT(*) AS n FROM product_translations").get().n
    : 0;
  return {
    productCount: Array.isArray(products) ? products.length : 0,
    catalogVersion: Number(settings.catalogVersion || 0),
    enabledLanguages: settings.enabledLanguages || ["ru"],
    glossaryCount,
    translationCount,
  };
}

export function dryRunProductAutoImportReadOnly(manifestPath, dbPath, expected = {}) {
  if (!existsSync(dbPath)) {
    throw new Error(`DB_PATH does not exist: ${dbPath}`);
  }
  if (lstatSync(dbPath).isSymbolicLink()) {
    throw new Error("Refusing symlink DB_PATH for dry-run.");
  }
  const resolvedDb = realpathSync(path.resolve(dbPath));
  const beforeFile = fileIdentity(resolvedDb);
  const db = new DatabaseSync(resolvedDb, { readOnly: true });
  let beforeSemantic;
  let report;
  try {
    beforeSemantic = semanticDbFingerprint(db);
    const products = readJsonState(db, "products") || [];
    const glossary = readGlossary(db);
    const translations = readTranslations(db);
    const loaded = loadAutoImportManifest(manifestPath, expected);
    const ctx = precomputeImportContext(products, glossary, translations);
    const mismatch = fingerprintMismatch(loaded, ctx);
    if (mismatch) {
      const error = new Error(mismatch);
      error.code = mismatch;
      throw error;
    }
    if (expected.runId && expected.runId !== loaded.manifest.runId) {
      const error = new Error("RUN_ID_MISMATCH");
      error.code = "RUN_ID_MISMATCH";
      throw error;
    }
    if (expected.fingerprint && expected.fingerprint !== artifactFingerprint(loaded)) {
      const error = new Error("ARTIFACT_FINGERPRINT_MISMATCH");
      error.code = "ARTIFACT_FINGERPRINT_MISMATCH";
      throw error;
    }
    const counts = summarizeClassification(loaded, ctx);
    const fatal =
      counts.staleSource +
      counts.unknownProduct +
      counts.invalidLocale +
      counts.invalidField +
      counts.numericMismatch +
      counts.protectedMismatch +
      counts.emptyValue;
    report = {
      mode: "dry-run",
      writes: 0,
      readOnly: true,
      runId: loaded.manifest.runId,
      artifactBaseSha: loaded.manifest.baseMainSha || "",
      artifactCatalogFingerprint: loaded.manifest.wholeCatalogSourceFingerprint,
      currentCatalogFingerprint: ctx.catalogFingerprint,
      artifactGlossaryFingerprint: loaded.manifest.glossaryFingerprint,
      currentGlossaryFingerprint: ctx.glossaryFingerprint,
      catalogMatch: true,
      glossaryMatch: true,
      fatal,
      ...counts,
    };
  } finally {
    db.close();
  }
  const afterFile = fileIdentity(resolvedDb);
  const afterDb = new DatabaseSync(resolvedDb, { readOnly: true });
  let afterSemantic;
  try {
    afterSemantic = semanticDbFingerprint(afterDb);
  } finally {
    afterDb.close();
  }
  if (beforeFile.size !== afterFile.size || beforeFile.mtimeMs !== afterFile.mtimeMs) {
    throw new Error("Dry-run mutated the SQLite file.");
  }
  if (JSON.stringify(beforeSemantic) !== JSON.stringify(afterSemantic)) {
    throw new Error("Dry-run mutated semantic DB fingerprints.");
  }
  return {
    ...report,
    fileIdentity: afterFile,
    semanticFingerprint: afterSemantic,
  };
}
